"""Replace the practice track in curriculum.js with the imported modules."""
import io, json, re

mods = json.loads(io.open(".build/practice-modules.json", encoding="utf-8").read())
p = "courses/python/curriculum.js"
s = io.open(p, encoding="utf-8").read()

# Everything from the TRACK 2 banner to the closing "]\n  });" is regenerated.
start = s.index("      /* ==================================================================\n         TRACK 2")
end = s.rindex("\n    ]\n  });")

def esc(t):
    return t.replace("\\", "\\\\").replace('"', '\\"')

out = ['''      /* ==================================================================
         TRACK 2 — CODING PRACTICE
         ------------------------------------------------------------------
         Imported from the Coding Practice source set: 3,293 problems with
         hidden answers, re-rendered through this design system.

         Generated by .build/import-practice.py, which also writes the
         lesson files under lessons/practice/. Do not hand-edit either —
         change the importer and re-run it.
         ================================================================== */
''']

for i, m in enumerate(mods):
    out.append('      {\n')
    out.append('        id: "%s", short: "%s", track: "practice", numPrefix: "C",\n' % (m["id"], m["short"]))
    out.append('        phase: "%s",\n' % esc(m["phase"]))
    out.append('        title: "%s",\n' % esc(m["title"]))
    out.append('        blurb: "%s",\n' % esc(m["blurb"]))
    out.append('        outcome: "%s",\n' % esc(m["outcome"]))
    out.append('        lessons: [\n')
    rows = []
    for l in m["lessons"]:
        rows.append(
            '          { id: "%s", title: "%s", difficulty: "%s", minutes: %d, tier: "%s",\n'
            '            summary: "%s",\n'
            '            keywords: [%s] }'
            % (l["id"], esc(l["title"]), l["difficulty"], l["minutes"], l["tier"],
               esc(l["summary"]),
               ", ".join('"%s"' % esc(k) for k in l["keywords"])))
    out.append(",\n".join(rows))
    out.append("\n        ]\n      }")
    out.append(",\n\n" if i < len(mods) - 1 else "\n")

s = s[:start] + "".join(out) + s[end:]
io.open(p, "w", encoding="utf-8", newline="\n").write(s)
print("curriculum rewritten with %d practice modules, %d lessons"
      % (len(mods), sum(len(m["lessons"]) for m in mods)))
